runtime: nodejs
vm: true

env_variables:
  TWILIO_AUTH_TOKEN: c294fbe2a3a569a6c8bbb252907caf4e
  TWILIO_TEST_ACCOUNT_SID: ACd0807747a9df8c111f1f021f642b23c2
  TWILIO_TEST_AUTH_TOKEN: 15c6d448c2e7daca5a8a2e1d7496ef01
  MONGOLAB_URI: mongodb://thierry:e9900232@ds027345.mlab.com:27345/franke-dev
  SLACK_MARKETER_BOT_API_KEY: xoxb-68923012309-YstFm2dExS2YusEFAcYnCpPk
  SLACK_THIERRY_TEST_TOKEN_DISCOSHARE: xoxp-51179849733-51751494722-68950324674-b31c0f93d0
  FACEBOOK_APP_ID: '818342958265127'
  FACEBOOK_APP_SECRET: 951cb0fe7b416425e1a07b2f34309c49
  FACEBOOK_APP_ACCESS_TOKEN: 818342958265127|8eHqME0qgln3cW-eCa3ZcXgFPtY
  FACEBOOK_MY_ACCESS_TOKEN: EAALoR1FU8ycBAEJVc5kSxHLyWyywN9FyBZBaMtmJcCvHkE7mzwjDWWzIYm5O7SGMCaRSKdlPG3Uh0vvXHajYeI0Tu7aqJEJqLkCQMvE0pK9XJbAAefLglwrqv41IFURYPR46cKZCnffyRuuQRZBmWoA56ZCkkjYZD
  FACEBOOK_MY_PAGE_ACCESS_TOKEN: EAALoR1FU8ycBACX6u317pHj9FdfM2WYuHJK5Nbzg7X3Edb0VFZA2pEZCOWiKPGfPzETqn0aRxtZADl79OwivCrRnoPqwv4nejZCbKlehZAEPSgKP0DZB1phI6NTYl2U2tw9l8YGUKATpFCy6gvGR1VZC5JCbIDKIBSLk6GFZCnodtwZDZD
  FACEBOOK_MY_PAGE_ACCESS_TOKEN_WHITEFRAME: EAALoR1FU8ycBAJvqJ2IZB9VaTkQiK3c7zksY4x58uyKIWIlymcijhRpUKSa5Ivl82KwApv45ie3MRKUJQ6oZBUQEgRCbrZCrjGyzmvntcgjjb2pvZA4sQJ9PbZByZBe0PZCrHq7rAr1ANwPqVSWjt9nZCamF0iYN4SQT7ZA1bWs2pEQZDZD
  SLACK_APP_CLIENT_ID: '51179849733.71136374771'
  SLACK_APP_CLIENT_SECRET: c37738ba685f7b018fe821aa8a8071a9
  SLACK_PORT: '3001'
  WIT_TOKEN: M7GIIFOOJXFOAKW2MMC372PXOEVOKFXK
  APIAI_TOKEN: 77a2401d5ca6462dae4de54ed1044523
  TWILIO_NUMBER: '+15146125723'
  WEBHOOK_VERIFY_TOKEN: marketer
  NODE_ENV: production

